# Generated by Django 4.2.5 on 2023-11-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blank',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
